baseURL = 'https://mason.dev/'
languageCode = 'en-us'
title = 'Mason Egger'
theme = 'megger'

copyright = "&copy; Mason Egger 2016 - 2022"

googleAnalytics = "G-885F33V7K6"

enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
#preserveTaxonomyNames = true
paginate = 7

pygmentsCodeFences = true

[outputs]
  home = [ "HTML", "CSS", "RSS" ]
  section = [ "HTML", "RSS" ]


[params]
  # Your details.
  name = "Mason Egger"
  bio = "On my business card, I am a Developer Advocate.  In my mind, I am an engineer. But in my heart, I am a teacher"

  # Date and time format (refer to Go's date format: http://fuckinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Jan 2, 2006"
  #   Examples: "3:04 pm" or "15:04"
  time_format = "3:04 PM"

  # Enable native social sharing buttons?
  sharing = true

  description = "The works and writings of Mason Egger"
  images = ['/img/mmeg.png']

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/MasonEgger"
    text = "Github"

  [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "//twitter.com/masonegger"
    text = "Twitter"

  [[params.social]]
    icon = "youtube"
    icon_pack = "fa"
    link = "//www.youtube.com/MasonEgger"
    text = "YouTube"

  #[[params.social]]
  #  icon = "twitch"
  #  icon_pack = "fa"
  #  link = "//www.twitch.tv/codingwithmason"
  #  text = "Twitch"

  [[params.social]]
    icon = "linkedin"
    icon_pack = "fa"
    link = "//linkedin.com/in/mason-egger"
    text = "LinkedIn"

  [[params.social]]
    icon = "file"
    icon_pack = "far"
    link = "/docs/Mason_Egger_Resume_Dec_2022.pdf"
    text = "Resume"

# Taxonomies.
[taxonomies]
   tag = "tags"
   category = "categories"
