site_url: https://mason.dev
site_name: Mason Egger
site_author: Mason Egger
repo_url: https://github.com/masonegger/website
repo_name: masonegger/website
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  logo: static/img/mmeg.png
  favicon: static/img/favicon.png
  custom_dir: overrides
  locale: en
  features:
    - announce.dismiss
    # - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    # - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.path
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    # - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    - scheme: mme
copyright: Copyright &copy; 2018-2023 - Mason Egger

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true

nav:
  - Home: index.md
  - About: about/index.md
  - Blog: 
    - blog/index.md
  - Tutorials: 
    - tutorials/index.md
  - Speaking: 
    - speaking/index.md
  - Extras: extras/index.md

plugins:
  - search
  - social:
      cards_layout: default
      cards_layout_options:
        background_color: "#FEFAE0"
        color: "#283618"
  - tags:
      tags_file: tags.md
  - blog:
      blog_dir: blog
      blog_toc: true
      post_url_format: "{slug}"
  - rss:
      match_path: (blog|tutorials|speaking)/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags 
  - blog:
      blog_dir: tutorials
      blog_toc: true
      post_url_format: "{slug}"
  - blog:
      blog_dir: speaking
      blog_toc: true
      post_url_format: "{slug}"



extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/masonegger
      name: Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mason-egger
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/MasonEgger
    - icon: fontawesome/brands/github
      link: https://github.com/MasonEgger
    - icon: fontawesome/regular/file
      link: static/docs/MasonEgger-resume.pdf
    - icon: fontawesome/solid/square-rss
      link: ./feed_rss_created.xml
      name: RSS
  analytics:
    provider: google
    property: G-885F33V7K6
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

# Color Scheme
# 606C38
# 283618
# FEFAE0
# DDA15E
# BC6C25